### PR TITLE
implementation for #47: let the formatting function know which ..

### PR DESCRIPTION
**Pull request by tenuki**
link is rendering.

### CODE REVIEW

**Comment by martinlissmyr** [comment]
Awesome. Well done! 

Would you mind adding a test?

**Comment by tenuki** [comment]
I already did. Do you mean something more specific to check link's content itself?

**Comment by martinlissmyr** [comment]
Oh, sorry... I was too quick... Then it's all good.

**Comment by tenuki** [comment]
No problem, thank you!!

**Pull request merged**
