### PR TITLE
allow `includeLevel` to accept an array of levels

### PR DESCRIPTION
**Pull request by ferllings**
See Issue #3

### CODE REVIEW

**Comment by martinlissmyr** [comment]
@ferllings Looking good. If you update the readme with expected output and info about the changed API I will merge and release. Also, please squash the commits into only one.

**Comment by mbforbes** [comment]
friendly ping @ferllings

**Comment by ferllings** [comment]
I can't figure out how to properly rebase the commits. I still have 2 commits with the same description

**Comment by martinlissmyr** [comment]
'Git rebase -i HEAD~2' and the force push

**Comment by ferllings** [comment]
Done

**Comment by martinlissmyr** [comment]
Thanks!

**Pull request merged**
