### PR TITLE
Fixing issue #33

### PR DESCRIPTION
**Pull request by GiridharanNarayanan**
####Issue: 
#33 

####Fix:
Update the `state.pos` correctly after encountering the [[toc]]

### CODE REVIEW

**Comment by GiridharanNarayanan** [comment]
The tests were always failing in my setup due to some line ending setting in my machine, since it is windows machine. It would you really helpful if you can try out the tests once in your setup with this fix.
I have manually validate all the test scenarios though.

**Comment by martinlissmyr** [comment]
Tests passes on my machine. Thanks!

If you get rid of that merge commit I will merge and release!

**Comment by GiridharanNarayanan** [comment]
I have updated the commits and have gotten rid of the merge commit. Thanks for trying out the tests.

**Comment by GiridharanNarayanan** [comment]
Would this also need a version update? Please let me know and I shall update accordingly.

**Comment by GiridharanNarayanan** [comment]
@martinlissmyr , Apologies for the rush. Could you please have a look at the final change? We are in need of this fix for our immediate release :)

**Pull request merged**
