### PR TITLE
Changed ul to ol

### PR DESCRIPTION
**Pull request by felixsanz**
A table of contents is an ordered list of elements, their order is not going to change and it's more like chapters. (chapter 1, chapter 2, etc).

Thanks!

### CODE REVIEW

**Comment by martinlissmyr** [comment]
I'm not so sure it's that black and white... WCAG 2 for example does not specify the use of an ordered list as a criteria:

"Check that the values and order of the entries in the table of contents correspond to the names and order of the sections of the document."
See https://www.w3.org/TR/WCAG20-TECHS/G64.html... 

W3C themselves use UL, see https://www.w3.org/TR/WCAG20/#contents

However, I can see your point. How about making it an option?

**Comment by felixsanz** [comment]
Would be nice, an option like `type: ol`, `type: ul`.

Anyway I think the w3 is wrong here because they are not even using the circles (bullet style), they are using the numeric style. And that numbers are ordered (1.1, 1.2...). So... i think they made an human mistake.

I prefer the whatwg spec, they are more open among other things. You can check here: https://html.spec.whatwg.org/multipage/

They use `<ol>` for their table of contents, which is expected.

To be honest, the option sounds nice just to avoid anyone being discomfort, but a table of contents is always an ordered set of elements.

You pick! :)

**Comment by felixsanz** [comment]
In the w3 HTML 4 spec they also use `ol`: https://www.w3.org/TR/html401/
But in the  w3 HTML 5 spec they use `ul` (https://www.w3.org/TR/html5/)

I wouldn't trust this guys to be honest, they doesn't seem to have consistency at all, hah :smile:

**Comment by martinlissmyr** [comment]
> Anyway I think the w3 is wrong here because they are not even using the circles (bullet style), they are using the numeric style. 

Well, they actually don't use any style at all. The numbers are part of the titles of the items the table of content refers to. And while I basically I agree with your position that "a table of contents is always an ordered set of elements" using a `OL` might be confusing in the case where you have sections/headings that are numbered in the way they are in https://www.w3.org/TR/WCAG20/#contents... Note that the first heading is not actually numbered 1.

If you were to use `OL` in that case you would get:

``` html
<ol>
  <li>Introduction</li>
  <li>
    WCAG 2.0 Guidelines
    <ol>
        <li>
          1 Percievable
          <ol>
            <li>1.1 Provide text alternatives for any non-text content so that it can be changed into other forms people need, such as large print, braille, speech, symbols or simpler language.</li>
            <li>1.2 PProvide alternatives for time-based media.</li>
          </ol>
        </li>
    </ol>
</ol>
```

Which would become:

<ol>
  <li>Introduction</li>
  <li>
    WCAG 2.0 Guidelines
    <ol>
        <li>
          1 Percievable
          <ol>
            <li>1.1 Provide text alternatives for any non-text content so that it can be changed into other forms people need, such as large print, braille, speech, symbols or simpler language.</li>
            <li>1.2 PProvide alternatives for time-based media.</li>
          </ol>
        </li>
    </ol>
</ol>

So, yeah... As I said... While I agree with you in principle I'm not sure it always will make sense.

This makes me think that an option may be the way to go.

**Comment by felixsanz** [comment]
Sure, the option is just a solution that will make everyone happy.

**Pull request closed without merging**
